export const SOCIAL_LINKS = {
  DISCORD: "https://discord.gg/Hu3FxfHnZt",
  INSTAGRAM: "https://www.instagram.com/wlooquantclub/",
  LINKEDIN: "https://linkedin.com/company/waterloo-quant-club",
  EMAIL: "mailto:info@waterlooquantclub.com",
} as const;

export interface MemberInfo {
  name: string;
  role: string;
  program: string;
  bio?: string;
  image?: string;
  linkedin?: string;
  email?: string;
  website?: string;
}

export const TEAM: MemberInfo[] = [
  {
    name: "Harry Jiang",
    role: "President",
    program: "Statistics",
    bio: "I'm a 5th year Statistics student, and a Quant Trader at Jane Street. I love sports, photography, and cubing!",
    image: "harry_jiang.jpg",
    linkedin: "https://www.linkedin.com/in/harryjiang7/",
    email: "harryjiang@waterlooquantclub.com",
  },
  {
    name: "Ian Zhao",
    role: "VP Tech",
    program: "Computer Science, Combinatorics & Optimization",
    bio: "I'm a CS + CO student and a SWE at HRT. When I'm not thinking about systems programming or programming languages, I enjoy running, reading, and everything music!",
    image: "ian_zhao.jpg",
    linkedin: "https://www.linkedin.com/in/ian-zhao/",
    email: "ianzhao@waterlooquantclub.com",
  },
  {
    name: "Daniel Shen",
    role: "VP Trading",
    program: "Computer Science",
    image: "daniel_shen.png",
  },
  {
    name: "Samantha La",
    role: "VP Logistics",
    program: "Systems Design Engineering",
    bio: "Hi! I’m Sam and studying Systems Design Engineering! I put the S in S&T and I love collecting smiskis:)",
    image: "sam_la.jpg",
    linkedin: "https://www.linkedin.com/in/samanthala/",
    email: "samanthala@waterlooquantclub.com",
  },
  {
    name: "John Huang",
    role: "VP Research",
    program: "Computer Science, Mathematical Finance",
    bio: "I'm a CS + Math Finance student and a Quant Researcher at Cubist. I love reading, strategy games, and word puzzles.",
    image: "john_huang.jpg",
  },
  {
    name: "Angelina Wu",
    role: "Creative Design",
    program: "Software Engineering",
  },
  {
    name: "Richard Yang",
    role: "Advisor",
    program: "Computing and Financial Management",
    bio: "Mathematics student working in finance, serving as advisor within the club",
    image: "richard_yang.jpg",
    linkedin: "https://www.linkedin.com/in/richardyang03/",
    email: "richard.yang1@uwaterloo.ca",
  },
  {
    name: "Kenneth Xiao",
    role: "Industry Relations",
    program: "Pure Mathematics",
    bio: "I like tea, math, and games. Previously at Point72.",
    image: "kenneth_xiao.jpg",
    linkedin: "https://www.linkedin.com/in/kdxiao",
    email: "kdxiao@uwaterloo.ca",
  },
  {
    name: "Soham Parmar",
    role: "Industry Relations",
    program: "Computer Engineering",
    bio: "I'm a Computer Engineering student with experience at Jane Street and an interest in software engineering, trading, and the world of finance.",
    image: "soham_parmar.jpg",
    linkedin: "https://www.linkedin.com/in/soham-parmar",
    email: "s24parma@uwaterloo.ca",
  },
  {
    name: "Marcus Lee",
    role: "External Relations",
    program: "Mathematics, Economics",
    bio: "I'm a Math and Econ student with an interest in finance. In my free time, I enjoy hiking and eating!",
    image: "marcus_lee.jpg",
    linkedin: "https://www.linkedin.com/in/marcus-lee-4355aa214/",
    email: "mys2lee@uwaterloo.ca",
  },
  {
    name: "Aurora Shi",
    role: "General Executive",
    program: "Software Engineering",
    bio: "Software Engineering student with 2x internships at Bloomberg. I love baking + painting, check out my website to see!",
    image: "aurora_shi.jpg",
    linkedin: "https://www.linkedin.com/in/ashi16/",
    email: "aurorashi16@gmail.com",
    website: "https://aurorashi.com/",
  },
  {
    name: "Patrick Huang",
    role: "General Executive",
    program: "Software Engineering",
    bio: "30x'd trading marbles in elementary school. In my free time, I like eating food.",
    image: "patrick_huang.jpg",
    linkedin: "https://www.linkedin.com/in/patrick-y-huang/",
    email: "patrick.huang@uwaterloo.ca",
    website: "https://www.patrickhuang.co/",
  },
  {
    name: "Alex Oláh",
    role: "General Executive",
    program: "Masters of Accounting",
    bio: "EY Tax",
    image: "alex_olah.jpg",
    linkedin: "https://www.linkedin.com/in/alexolah",
  },
  {
    name: "Joshua Liu",
    role: "Tech Executive",
    program: "Computer Science",
    bio: "Hi, I am a competitive programmer turned CTF player turned SWE at HRT. I love homelabbing, climbing, and cooking!",
    image: "joshua_liu.jpg",
    linkedin: "https://www.linkedin.com/in/joshua-liu-265681220/",
    email: "joshliu@waterlooquantclub.com",
  },
  {
    name: "Amelie Zhou",
    role: "General Executive",
    program: "Mathematics",
    bio: "I like solving puzzles and exploring alternative subcultures. I also sometimes write actuarial exams.",
    image: "amelie_zhou.jpg",
    linkedin: "https://www.linkedin.com/in/amelie-zhou",
    email: "amelieezhou@gmail.com",
  },
  {
    name: "Moses Xu",
    role: "Tech Executive",
    program: "Computer Science",
    bio: "✨ parallel programming enjoyer ✨ ( I also like tetris, MC, bad jokes, and anything artsy :) )",
    image: "moses_xu.jpg",
    linkedin: "https://www.linkedin.com/in/moses-xu",
    email: "moses.xu@uwaterloo.ca",
  },
  {
    name: "Megan Wu",
    role: "Design Executive",
    program: "Systems Design Engineering",
    bio: "I'm a Systems Design engineering student with experience in SWE. In my free time, I love travelling, puzzles, and drawing!",
    image: "megan_wu.jpg",
    linkedin: "https://www.linkedin.com/in/megan-bx-wu/",
    email: "meganwu@waterlooquantclub.com",
  },
  {
    name: "Gordon Wang",
    role: "Tech Executive",
    program: "Computing and Financial Management",
    bio: "I'm a CS + Finance student with previous SWE experience at Microsoft and Shopify. I love soccer, football, and MMA.",
    image: "gordon_wang.jpg",
    linkedin: "https://www.linkedin.com/in/gordon-wang-ab785b237/",
    email: "gordonwang@waterlooquantclub.com",
  },
  {
    name: "Caroline Lu",
    role: "Junior Executive",
    program: "Mathematics",
    bio: "I'm a math student planning to declare data science. I love tennis, reading, singing, and anything to do with music.",
    image: "caroline_lu.jpg",
    linkedin: "https://www.linkedin.com/in/yiyang-lu-caroline",
    email: "carolinelu@waterlooquantclub.com",
  },
  {
    name: "Michael Parker",
    role: "Junior Executive",
    program: "Mathematics/BBA",
    bio: "Hi I'm Michael Parker, in 2A Math/BBA(WLU) majoring in Statistics & Finance. A fun fact about me is 2/3 of my pets are named after other animals.",
    image: "michael_parker.jpg",
    linkedin: "https://www.linkedin.com/in/michael-parker-7000a22a1/",
    email: "michaelparker@waterlooquantclub.com",
  },
  {
    name: "Jason Hon",
    role: "Social Media Executive",
    program: "Computer Science",
    bio: "Computer Science student with a Minecraft YouTube channel. Checkout my website!",
    image: "jason_hon.jpg",
    linkedin: "https://www.linkedin.com/in/jasonhonhk/",
    email: "jasonhon@waterlooquantclub.com",
    website: "https://jasonhon.com/",
  },
  {
    name: "David Kachroo",
    role: "Junior Executive",
    program: "Computing and Financial Management",
    bio: "I'm a CS + Finance (CFM) student in 1B and a Junior Exec for WQC. I enjoy investing, brain teasers (QuantPrep), and coding side projects",
    image: "david_kachroo.png",
    linkedin: "https://www.linkedin.com/in/david-kachroo/",
    email: "davidkachroo@waterlooquantclub.com",
  },
  {
    name: "Elaine Li",
    role: "Junior Executive",
    program: "Computing and Financial Management",
    bio: "On coop term after CFM 2A right now, a fun fact is I'm been on top of a wind turbine",
    image: "elaine_li.jpg",
    linkedin: "https://www.linkedin.com/in/elaine-qy-li",
    email: "elaine.li@waterlooquantclub.com",
  },
  {
    name: "Ian Leung",
    role: "Junior Executive",
    program: "Computing and Financial Management",
    bio: "1B CFM, fun fact: i have 2 cats",
    image: "ian_leung.jpg",
    linkedin: "https://www.linkedin.com/in/ianleung12/",
    email: "ianleung@waterlooquantclub.com",
  },
  {
    name: "Matthew Yang",
    role: "General Executive",
    program: "Computing and Financial Management",
    bio: "aspiring renaissance man",
    image: "matthew_yang.jpeg",
    linkedin: "https://www.linkedin.com/in/matthew--yang/",
    email: "matthewyang@waterlooquantclub.com",
    website: "https://matthewyang.ca/",
  },
];
